#! /bin/bash

# Build structured tree of html refs

DIR="$1"
SHORT="${DIR/www/}"
INDEX="$DIR/index.html"
ROOT="$( echo "$SHORT" | sed -E 's,[a-zA-Z0-9]+,..,g ; s,^,../,' )"

: > "$INDEX"
echo "\
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>vanille :: $SHORT</title>
    <link rel=\"stylesheet\" type=\"text/css\" href=\"$ROOT/style.css\">
    <link rel=\"stylesheet\" type=\"text/css\" href=\"$ROOT/colorcodes.css\">
</head>

<body class=\"f9 b9\">
    <pre>
<span class=\"bold\"><span class=\"f2\">\$</span></span> \
<span class=\"f3\"><span class=\"bold\">exa</span> -Flah</span> \
<span class=\"bold\"><span class=\"f4\">$SHORT</span></span>
" >> "$INDEX"

exa -lahF --color=always "$DIR" |
ansi2html --bg=dark --body-only >> "$INDEX"
sed -i '/.html/d' "$INDEX"
sed -Ei 's,<span class="underline"><([^>]+)>,<\1><span class="underline">,g' "$INDEX"
sed -Ei 's,^(.*Permissions),<span class="underline">Link</span> \1,' "$INDEX"

for f in $( /bin/ls "$DIR" ); do
    if [[ "$f" =~ .*html ]]; then
        continue
    fi
    if [ -d "$DIR/$f" ]; then
        sed -Ei "s,(.*$f),[<a href=\"$f/index.html\">::</a>] \1," "$INDEX"
    else
        link="$f"
        case "$( file "$DIR/$f" )" in
            (*text*|*Unicode*|*ASCII*)
                link="$link.html"
                ;;
            (*) ;;
        esac
        sed -Ei "s,(.*$f),[<a href=\"$link\">::</a>] \1,g" "$INDEX"
    fi
done

echo "\

[<a href=\"../index.html\">::</a>] \
<span class=\"f4\"><span class=\"bold\">..</span></span>
[<a href=\"$ROOT/index.html\">::</a>] \
<span class=\"f4\"><span class=\"bold\">/</span></span>
[<a href=\"$ROOT/share/index.html\">::</a>] \
<span class=\"f4\"><span class=\"bold\">/share</span></span>


<span class=\"bold\"><span class=\"f2\">\$</span></span> \
<span class=\"f3\"><span class=\"bold\">tree</span> -Ca</span> \
<span style=\"line-height:1\">
" >> "$INDEX"

cd "$DIR"
tree -aC -I '*html' |
ansi2html --bg=dark --body-only >> 'index.html'
cd -

echo "\
</span></pre></body>
" >> "$INDEX"
