#! /bin/bash

# Synchronizes files by copying them from the specified location
# input:
# | foo/
# |     bar/
# |         a.txt: stuff/a
# |     b.txt: more/things/b
#
# output:
# | www/share/foo/bar/a.txt: /home/<user>/stuff/a
# |     cp $< $@
# |
# | www/share/foo/b.txt: /home/<user>/more/things/b
# |     cp $< $@

echo '# makefile autogenerated by sync.sh'
DIR=()

while IFS= read line; do
    # count directory depth from indentation
    let 'offset = 0'
    while [[ "$line" =~ ^'    ' ]]; do
        let 'offset++'
        line="${line#    }"
    done
    if [[ "$line" =~ /$ ]]; then
        # append a new directory at the correct depth
        DIR[$offset]="$line"
    else
        # generate a new dependency from the current path prefix
        echo -n "www/share/${DIR[@]:0:$offset}" | tr -d ' '
        echo "$line" | sed "s,: ,: $HOME/,"
        echo -e "\tcp \$< \$@"
        echo
    fi
done < sharelist
