#! /bin/bash

echo '# makefile autogenerated by sync.sh'

DIR=()
while IFS= read line; do
    #echo ">> $line"
    let 'offset = 0'
    while [[ "$line" =~ ^'    ' ]]; do
        let 'offset++'
        line="${line#    }"
    done
    if [[ "$line" =~ /$ ]]; then
        #echo "dir with offset $offset"
        DIR[$offset]="$line"
        #echo "${DIR[@]:0:$(($offset+1))}" | tr -d ' '
    else
        #echo "file with offset $offset"
        echo -n "www/share/${DIR[@]:0:$offset}" | tr -d ' '
        echo "$line" | sed "s,: ,: $HOME/,"
        echo -e "\tcp \$< \$@"
        echo
    fi
done < sharelist
