compile-raw SRC TGT:
  typst compile --features html --format html --root=.. {{SRC}} {{TGT}}

watch-raw SRC TGT:
  typst watch --features html --format html --root=.. --no-serve {{SRC}} {{TGT}}

compile BASE:
  just compile-raw _src/pages/{{BASE}}.typ {{BASE}}.html

watch BASE:
  just watch-raw _src/pages/{{BASE}}.typ {{BASE}}.html

compile-all:
  ls _src/pages | cut -d. -f1 | parallel --lb just compile {}

watch-all:
  ls _src/pages | cut -d. -f1 | parallel --lb just watch {}

