#! /bin/bash

FROM=
INTO=
RULES=()
PHONY=()

if [ -n $TARGET ]; then
    : > $TARGET
fi

from() {
    FROM=( "$1" )
}
into() {
    INTO=( "$1" )
    mkdir -p "$1"
}
path() {
    for p in "$@"; do
        echo -n "/$p"
    done
}
build() { echo -e "$1" >> $TARGET; }
build "# Autogenerated Makefile"

from_push() {
    FROM+=( "$1" );
}
from_pop() {
    if [[ "${FROM[-1]}" == "$1" ]]; then
        unset FROM[-1];
    else
        echo "ERROR: Mismatched closing directory in FROM"
        echo "       Expected '${FROM[-1]}'"
        echo "       Actual   '$1'"
    fi
}
into_push() {
    INTO+=( "$1" );
    build "$( path "${INTO[@]}" ):"
    build "\tmkdir -p \$@"
}
into_pop() {
    if [[ "${INTO[-1]}" == "$1" ]]; then
        unset INTO[-1];
    else
        echo "ERROR: Mismatched closing directory in INTO"
        echo "       Expected '${INTO[-1]}'"
        echo "       Actual   '$1'"
    fi
}
alias 'from++'='from_push'
alias 'from--'='from_pop'
alias 'into++'='into_push'
alias 'into--'='into_pop'

